version: '3.8'

services:
  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    ports:
      - 6379:6379
      - 16379:16379
    networks:
      - redis_cluster

networks:
  redis_cluster:
